/**
	Generated by sails-inverse-model
	Date:Sat Apr 14 2018 13:40:41 GMT+0530 (India Standard Time)
*/

module.exports = {
    attributes: {
       
        business: {
            model:'Businesses',
            columnName:'business_id',
            required:true
        },
        dealer_id: {
            type: 'string',
            required: true
        },
        digital_order_product_id: {
            type: 'string',
            required: true
        },
        quantity: {
            type: 'number',
            required: true
        },
        websales_id: {
            type: 'string',
            required: true
        },
        websales_status: {
            type: 'string',
            required: true
        },
        websales_order_updated_at: {
            type: 'string',
            required: true
        },
        delivered_at: {
            type: 'string',
            required: true
        },
        status: {
            type: 'string',
            required: true
        },
        accepted_quantity: {
            type: 'number',
            required: true
        }
    }
};