/**
	Generated by sails-inverse-model
	Date:Sat Apr 14 2018 13:40:41 GMT+0530 (India Standard Time)
*/

module.exports = {
    attributes: {
       
        country_id: {
            type: 'number',
            required: true
        },
        name: {
            type: 'string',
            required: true
        },
        status: {
            type: 'boolean',
            required: true
        },
        
    }
};