/**
	Generated by sails-inverse-model
	Date:Sat Apr 14 2018 13:40:41 GMT+0530 (India Standard Time)
*/

module.exports = {
    attributes: {
        
        business: {
            model:'Businesses',
            columnName:'business_id',
            required:true
        },
        quantity: {
            type: 'number',
            required: true
        },
        cancelled: {
            type: 'boolean',
            required: false
        },
        deliver_at: {
            type: 'string',
            required: false
        },
        stowage: {
            type: 'boolean',
            required: true
        }
    }
};