/**
	Generated by sails-inverse-model
	Date:Thu Apr 05 2018 20:41:01 GMT+0530 (India Standard Time)
*/

module.exports = {
    attributes: {
        // id: {
        //     type: 'number',
        //     unique: true,
        //     autoIncrement: true
        // },
        name: {
            type: 'string',
            
        },
        quantity: {
            type: 'number',
            
        },
        business: {
            model:'Businesses',
            columnName:'business_id',
            required:true
        },
        // created_at: {
        //     type: 'string',
        //     autoCreatedAt: true,
        // },
        // updated_at: {
        //     type: 'string',
        //     autoCreatedAt: true,
        // },
        image_data_uri: {
            type: 'string',
            columnName:'image_data',
            allowNull:true
        },
        price: {
            type: 'number',
            columnName:'price_cents',
            allowNull:true
        },
        stock_tracked: {
            type: 'boolean',
            
        },
        position: {
            type: 'number',
            
        },
        material_code: {
            type: 'string',
            allowNull:true
        }
    }
};